function obj = makeattributestable(obj,forced)
    if nargin<2, forced=false; end
    if isempty(obj.table_attributes) || forced
        T=table(obj.c_cell_id,...
            obj.c_batch_id,...
            obj.c_cluster_id,...
            obj.c_cell_type_tx,...
            obj.c_cell_cycle_tx,...
            'VariableNames',{'CellID','BatchID','ClusterID',...
            'CellType','CellCycle'});
        if ~isempty(obj.list_cell_attributes)
            for k=1:2:length(obj.list_cell_attributes)
            T = addvars(T,obj.list_cell_attributes{k+1},...
                'NewVariableNames',obj.list_cell_attributes{k});
            end
        end
        obj.table_attributes=T;
        disp('table_attributes made.');
    else
        disp('table_attributes existed.');
    end
end
