    function [button1, button2] = gui_createbuttons(parentfig, in_sc_openscedlg)
        fig_pos = get(parentfig, 'Position'); 
        fig_width = fig_pos(3);
        fig_height = fig_pos(4);
        btn_width = 100; 
        btn_height = 25;
        btn_x = (fig_width - btn_width) / 2;
        btn_y = (fig_height - btn_height) / 1.618;
        
        button1 = uicontrol('Parent', parentfig,...
            'Style', 'pushbutton',...
            'Units', 'pixels',...
            'Position', [btn_x btn_y btn_width btn_height],...
            'String', 'Import Data...',...
            'Callback', in_sc_openscedlg,...
            'ButtonDownFcn', in_sc_openscedlg,...
            'KeyPressFcn', in_sc_openscedlg, 'Tooltip','Click or Press i');
        
        button2 = uicontrol('Parent', parentfig,...
            'style','text',...
            'Units', 'pixels',...
            'position', [btn_x btn_y+25 btn_width btn_height],...
            'FontSize', 9,...    
            'string','Ready to explore.');
        if get(parentfig,'AutoResizeChildren')==0
            set(parentfig,'resizefcn',{@gui.gui_myresizefun, button1, button2});
        end
    end