function [titxt] = i_getsubtitle(c)
    titxt = sprintf('(%s/%s = %.2f%% nonzero)', ...
        num2bankScalar(sum(c > 0)), ...
        num2bankScalar(numel(c)), ...
        100*sum(c > 0)./numel(c));
end