function [titxt] = i_getsubtitle(x, sampleid)
    if nargin<2, sampleid=''; end
    if issparse(x), x = full(x); end
    if ~isempty(sampleid)
    titxt = sprintf('%s (%s/%s = %.2f%% nonzero)', ...
        sampleid, ...
        num2bankScalar(sum(x > 0)), ...
        num2bankScalar(numel(x)), ...
        100*sum(x > 0)./numel(x));
    titxt = strrep(titxt,'_','\_');
    else
    titxt = sprintf('(%s/%s = %.2f%% nonzero)', ...
        num2bankScalar(sum(x > 0)), ...
        num2bankScalar(numel(x)), ...
        100*sum(x > 0)./numel(x));
    end

end