function [titxt] = i_getsubtitle(x)
    if issparse(x), x = full(x); end
    titxt = sprintf('(%s/%s = %.2f%% nonzero)', ...
        num2bankScalar(sum(x > 0)), ...
        num2bankScalar(numel(x)), ...
        100*sum(x > 0)./numel(x));
end