function [glist, setname, Col, ctag] = i_selectMSigDBGeneSets(species, ...
    colnoly, parentfig)
%I_SELECTMSIGDBGENESETS Pick an MSigDB collection, then gene sets from it.
%   [glist, setname, Col, ctag] = gui.i_selectMSigDBGeneSets(species, colnoly, parentfig)
%   SPECIES is 'human'/'hs' or 'mouse'/'mm'; empty asks the user. With
%   COLNOLY true it stops after the collection: Col is the decoded JSON and
%   ctag its tag ('H', 'C2', 'M5', ...). Otherwise the user picks one or more
%   gene sets: setname is a cell array of their names and glist a cell array
%   holding each set's genes as a string array.
%
%   This replaces gui.i_selectMSigDBGeneSet, a single-choice copy whose
%   gene-set list showed the collection names instead of the sets.

if nargin < 3, parentfig = []; end
if nargin < 1, species = 'human'; end
if nargin < 2, colnoly = false; end

glist = [];
setname = [];
Col = [];
ctag = [];

if isempty(species)
    species = gui.i_selectspecies(2, false, parentfig);
    if isempty(species), return; end
end

switch lower(species)
    case {'human', 'hs'}
        listitems = {'H: hallmark gene sets', 'C1: positional gene sets', ...
            'C2: curated gene sets', ...
            'C3: regulatory target gene sets', ...
            'C4: computational gene sets', ...
            'C5: ontology gene sets', ...
            'C6: oncogenic signature gene sets', ...
            'C7: immunologic signature gene sets', ...
            'C8: cell type signature gene sets'};

        urllist = {'https://scgeatool.github.io/data/msigdb/h.all.v2023.2.Hs.json', ...
            'https://scgeatool.github.io/data/msigdb/c1.all.v2023.2.Hs.json', ...
            'https://scgeatool.github.io/data/msigdb/c2.all.v2023.2.Hs.json', ...
            'https://scgeatool.github.io/data/msigdb/c3.all.v2023.2.Hs.json', ...
            'https://scgeatool.github.io/data/msigdb/c4.all.v2023.2.Hs.json', ...
            'https://scgeatool.github.io/data/msigdb/c5.all.v2023.2.Hs.json', ...
            'https://scgeatool.github.io/data/msigdb/c6.all.v2023.2.Hs.json', ...
            'https://scgeatool.github.io/data/msigdb/c7.all.v2023.2.Hs.json', ...
            'https://scgeatool.github.io/data/msigdb/c8.all.v2023.2.Hs.json'};
    case {'mouse', 'mm'}
        listitems = {'MH: hallmark gene sets', 'M1: positional gene sets', ...
            'M2: curated gene sets', ...
            'M3: regulatory target gene sets', ...
            'M5: ontology gene sets', ...
            'M8: cell type signature gene sets'};
        urllist = {'https://scgeatool.github.io/data/msigdb/mh.all.v2023.2.Mm.json', ...
            'https://scgeatool.github.io/data/msigdb/m1.all.v2023.2.Mm.json', ...
            'https://scgeatool.github.io/data/msigdb/m2.all.v2023.2.Mm.json', ...
            'https://scgeatool.github.io/data/msigdb/m3.all.v2023.2.Mm.json', ...
            'https://scgeatool.github.io/data/msigdb/m5.all.v2023.2.Mm.json', ...
            'https://scgeatool.github.io/data/msigdb/m8.all.v2023.2.Mm.json'};
    otherwise
        error('gui:i_selectMSigDBGeneSets:species', ...
            'MSigDB gene sets are available for human and mouse only, not "%s".', species);
end

if gui.i_isuifig(parentfig)
    [indx1, tf1] = gui.myListdlg(parentfig, listitems, 'Select MSigDB Collection:', [], false);
else
    [indx1, tf1] = listdlg('PromptString', ...
        {'Select MSigDB Collection:'}, ...
        'SelectionMode', 'single', 'ListString', listitems, ...
        'ListSize', [220, 300]);

end

if tf1 ~= 1, return; end
if pkg.i_isnetavl ~= 1
    gui.myErrordlg(parentfig, 'This function requires internet access to retrieve information needed.');
    return;
end


Col = webread(urllist{indx1});
ctag = listitems{indx1};
ctag = extractBefore(ctag, ':');
setnames = fields(Col);

if colnoly
    return;
end

if gui.i_isuifig(parentfig)
    [idx, tf] = gui.myListdlg(parentfig, setnames, 'Select gene set:', [], true);
else
    [idx, tf] = listdlg('PromptString', ...
        {'Select gene set:'}, ...
        'SelectionMode', 'multiple', ...
        'ListString', setnames, ...
        'ListSize', [260, 300]);
end
if tf == 1
    setname = setnames(idx);
    glist = cell(length(idx), 1);
    for k = 1:length(idx)
        glist{k} = string(Col.(setnames{idx(k)}).geneSymbols);
    end
end
