function [selecteditem] = i_selectcellscore

selecteditem=[];
selitems={'Expression of Gene', ...
    'TF Activity Score [PMID:33135076]',...
    'TF Targets Expression Score',...
    'Differentiation Potency [PMID:33244588]',...
    'MSigDB Signature Score',...
    '--------------------------------',...
    'Predefined Cell Score',...
    'Define New Score...',...
    '--------------------------------',...
    'Library Size','Other Attribute'};
[indx1,tf1]=listdlg('PromptString',...
    'Select a metric for comparison.',...
    'SelectionMode','single','ListString',selitems, ...
    'ListSize',[200,300]);
if tf1~=1, return; end

selecteditem=selitems{indx1};
end