function [selecteditem] = i_selectcellscore

selecteditem=[];
selitems={'Expression of Individual Genes',...
    '--------------------------------',...
    'TF Targets Expression Score...',...    
    'MSigDB Signature Score...',...
    'PanglaoDB Cell Type Marker Score...',...
    'More Predefined Score...',...
    'Define New Score...',...
    '--------------------------------',...
    'Differentiation Potency [PMID:33244588]',...
    'TF Activity Score [PMID:33135076] 🐢',...    
    '--------------------------------',...
    'Library Size of Cells',...
    'Other Cell Attribute...'};

    [indx1,tf1]=listdlg('PromptString',...
        'Select a metric for comparison.',...
        'SelectionMode','single','ListString',selitems, ...
        'ListSize',[220,300]);
    if tf1~=1, return; end
    
    selecteditem=selitems{indx1};
end