function [methodid, dim] = i_selnormmethod(parentfig)
if nargin<1, parentfig = []; end

methodid = []; 
dim =[];
if nargout > 1
    answer = gui.myQuestdlg(parentfig, 'Specify the dimension to operate on:', ...
        '', {'Row-wise', 'Column-wise'}, 'Row-wise');
    if isempty(answer), return; end
    switch answer
        case 'Column-wise'
            dim = 1;
        case 'Row-wise'
            dim = 2;
        otherwise
            return;
    end
end

listitems = {'zscore std', ...
    'zscore robust', ...
    'norm 2', ...
    'norm Inf', ...
    'scale std', ...
    'scale mad', ...
    'scale first', ...
    'scale iqr', ...
    'range [0 1]', ...
    'range [1 10]', ...    
    'center mean', ...
    'center median', ...
    'center scale', ...
    'medianiqr'};
if gui.i_isuifig(parentfig)
    [indx, tf] = gui.myListdlg(parentfig, listitems, 'Select Method');
else
    [indx, tf] = listdlg('PromptString', {'Select Method'}, ...
        'SelectionMode', 'single', ...
        'ListString', listitems, 'ListSize', [220, 300], ...
        'InitialValue', methodid);
end
if tf == 1
    methodid = indx;
end

end