function [methodid, dim] = i_selnormmethod(parentfig)
if nargin<1, parentfig = []; end
if ~isempty(parentfig) && pkg.i_isvalid(parentfig) && parentfig.Visible == "on"
    figure(parentfig);
    cleanupObj = onCleanup(@() gui.i_raisefig(parentfig));
end

methodid = [];
dim =[];
if nargout > 1
    answer = gui.myQuestdlg(parentfig, 'Specify the dimension to operate on:', ...
        '', {'Row-wise', 'Column-wise'}, 'Row-wise');
    if isempty(answer), return; end
    switch answer
        case 'Column-wise'
            dim = 1;
        case 'Row-wise'
            dim = 2;
        otherwise
            return;
    end
end

listitems = {'zscore std', ...
'zscore robust', ...
'norm 2', ...
'norm Inf', ...
'scale std', ...
'scale mad', ...
'scale first', ...
'scale iqr', ...
'range [0 1]', ...
'range [1 10]', ...
'center mean', ...
'center median', ...
'center scale', ...
'medianiqr'};
if gui.i_isuifig(parentfig)
    % allowmulti=false, explicitly. MYLISTDLG defaults it to TRUE, which
    % gave this dialog a multi-select listbox: ctrl-clicking a second
    % method returned a two-element INDX, and the SWITCH METHODID in
    % GUI.I_NORM4HEATMAP then threw 'SWITCH expression must be a scalar
    % or a character vector'. Only one method applies at a time.
    [indx, tf] = gui.myListdlg(parentfig, listitems, ...
        'Select Method', listitems(methodid), false);
else
    [indx, tf] = listdlg('PromptString', {'Select Method'}, ...
        'SelectionMode', 'single', ...
        'ListString', listitems, 'ListSize', [220, 300], ...
        'InitialValue', methodid);
end
if tf == 1
    methodid = indx;
end

end
