function [methodid, dim] = i_selnormmethod(FigureHandle)
if nargin<1, FigureHandle = []; end

methodid = []; 
dim =[];
if nargout > 1
    answer = gui.myQuestdlg(FigureHandle, 'Specify the dimension to operate on:', ...
        '', {'Row-wise', 'Column-wise'}, 'Row-wise');
    switch answer
        case 'Column-wise'
            dim = 1;
        case 'Row-wise'
            dim = 2;
        otherwise
            return;
    end
end

listitems = {'zscore std', ...
    'zscore robust', ...
    'norm 2', ...
    'norm Inf', ...
    'scale std', ...
    'scale mad', ...
    'scale first', ...
    'scale iqr', ...
    'range [0 1]', ...
    'range [1 10]', ...    
    'center mean', ...
    'center median', ...
    'center scale', ...
    'medianiqr'};
[indx, tf] = listdlg('PromptString', {'Select Method'}, ...
    'SelectionMode', 'single', ...
    'ListString', listitems, 'ListSize', [220, 300], ...
    'InitialValue', methodid);
if tf == 1
    methodid = indx;
end

end