function T = i_transformitems()
%I_TRANSFORMITEMS The transforms gui.i_transformx offers, in menu order.
%   T = gui.i_transformitems() returns a table with columns Key (a stable
%   name to preselect an item by) and Label (the menu text).
%
%   Callers should preselect by Key, as in
%       gui.i_transformx(X, true, "pearson_residuals", parentfig)
%   and not by position. Positions shift whenever an item is inserted:
%   adding "(d): Shifted CLR" moved Pearson residuals from 5 to 6, and three
%   callers that asked for 5 silently got DESeq instead.
%
%   See also gui.i_transformx.

T = table( ...
    ["libsize"; "log1p"; "libsize_log1p"; "shiftedclr"; "deseq"; ...
     "pearson_residuals"; "knn_smoothing"; "freeman_tukey"; "magic"; ...
     "sctransform_r"; "sctransform_matlab"], ...
    ["Library Size Normalization"; "Log(x+1) Transformation"; ...
     "(a) and (b)"; "Shifted CLR PFlog1pPF Normalization"; ...
     "DeSeq Normalization"; "Pearson Residuals Transformation"; ...
     "kNN Smoothing Transformation"; "Freeman-Tukey Transformation"; ...
     "MAGIC Imputation"; "SCTransform (R/Seurat, vst v2)"; ...
     "SCTransform (native MATLAB)"], ...
    'VariableNames', ["Key", "Label"]);

% The menu letters are derived, so inserting an item cannot leave them out
% of step with the list.
letters = string(num2cell(char('a' + (0:height(T) - 1))))';
T.Label = "(" + letters + "): " + T.Label;
end
