function T = grnmethods()
%GRNMETHODS The gene-network methods, one row each.
%   T = net.grnmethods() returns a table that is the single list of
%   network methods. sc_grn dispatches from it, the GUI menus
%   (gui.i_selectgrnmethod) and the CLI (cli.cmd_grn, cli.cmd_help) read
%   it, so a method is added by adding a row here and nowhere else.
%
%   Columns:
%     Key            name passed to sc_grn(X, Key)
%     Label          menu text
%     Summary        one-line description
%     Build          @(X, extra) -> genes-by-genes A; EXTRA is the cell of
%                    arguments after the key in sc_grn(X, Key, ...).
%                    A(i, j) is the edge from gene i to gene j: regulators
%                    in rows, as GENIE3, xicor and grnformer return it and
%                    as cli.cmd_grn (row = source) and net.i_makegraph
%                    (DIGRAPH, row -> column) read it
%     ExtraArgs      usage of the extra arguments, "" if it takes none
%     InMenus        offered in the GUI menus and the CLI
%     Transform      gui.i_transformitems Key to preselect in
%                    gui.i_transformx, e.g. "pearson_residuals"
%     RawCountsNote  warning shown when the input looks like raw counts,
%                    "" for none
%     SecondsPerPair run-time estimate per gene pair, NaN if not quadratic
%                    in the gene count
%
%   Every Build takes X as given. X arrives normalised and transformed --
%   the GUI runs gui.i_transformx and the CLI normalises first -- so no
%   Build may normalise it again. tests/grnMethodsTest.m checks that.
%
%   See also sc_grn, gui.i_selectgrnmethod.

rows = {
    % Key, Label, Summary, Build, ExtraArgs, InMenus, Transform, RawCountsNote, SecondsPerPair
    %
    % The PCR rows transpose: net.pcrnet's row k holds the
    % coefficients that predict gene k, so its rows are targets. The
    % scTenifold tools rely on that orientation (ten.i_knk reads A(k, j) as
    % the effect of j on k) and call net.pcrnet directly, so it stays as it
    % is and the registry turns it round. tests/grnDirectionTest.m.
    "pcrnet", "PCR (PC Regression)", ...
    "principal component regression, signed (parallel by default)", ...
    @(X, ~) net.pcrnet(X, 3, false, true, false, false, pkg.i_usegpu(X)).', ...
    "", true, "pearson_residuals", "", NaN

    "xicor", "Chatterjee Xi Correlation", ...
    "Chatterjee's xi correlation (nonlinear, directed)", ...
    @(X, ~) net.xicornet(X), ...
    "", true, "pearson_residuals", "", NaN

    "pearson", "Pearson Correlation", ...
    "thresholded Pearson correlation", ...
    @(X, ~) net.pearsonnet(X), ...
    "", true, "pearson_residuals", "", NaN

    "distcorr", "Distance Correlation", ...
    "distance correlation (nonlinear, symmetric)", ...
    @(X, ~) net.distcorrnet(X), ...
    "", true, "pearson_residuals", "", NaN

    "mi", "Mutual Information", ...
    "binned mutual information (parallel)", ...
    @(X, ~) net.minet(X), ...
    "", true, "pearson_residuals", "", NaN

    % Pairs are scored by a grid search: 0.2 s a pair at the 2000 cells
    % net.micnet uses, so 50 genes (1225 pairs) take about 4 minutes.
    "mic", "Maximal Information Coefficient (MIC)", ...
    "maximal information coefficient, MINE (nonlinear, symmetric)", ...
    @(X, ~) net.micnet(X), ...
    "", true, "pearson_residuals", "", 0.2

    % IDS was benchmarked on library-size normalised log1p data.
    % On simulated UMI data it scored AUROC 0.54-0.66 on raw counts against
    % 0.71-0.94 on normalised log1p: shared sequencing depth masquerades
    % as dependence.
    "ids", "InterDependence Score (IDS)", ...
    "InterDependence Score (nonlinear, fast)", ...
    @(X, ~) net.idsnet(X), ...
    "", true, "libsize_log1p", ...
    "IDS is unreliable on untransformed counts: differences in sequencing " + ...
    "depth make unrelated genes look dependent. Cancel and choose " + ...
    """(a) and (b)"" (library size normalization + log(x+1)), or continue anyway?", ...
    NaN

    % donorm = false: net.genie3 library-size normalises by default, which
    % on an already log1p'd matrix is not meaningful on either scale.
    "genie3", "GENIE3 (Random Forest)", ...
    "random forest ensemble (slow)", ...
    @(X, ~) net.genie3(X, [], false), ...
    "", true, "pearson_residuals", "", NaN

    "pcrnet_batch", "PCR (batch pagesvd)", ...
    "principal component regression, batched pagesvd", ...
    @(X, ~) net.pcrnet_batch(X).', ...
    "", false, "pearson_residuals", "", NaN

    % The one-SVD-per-gene net.pcrnet shipped up to v26.4.2; same network,
    % much slower. For benchmarking against the pcrnet row.
    "pcrnet_legacy", "PCR (original, per-gene SVD)", ...
    "principal component regression, one SVD per gene (slow)", ...
    @(X, ~) net.pcrnet_legacy(X, 3, false, true, false, false, pkg.i_usegpu(X)).', ...
    "", false, "pearson_residuals", "", NaN

    % donorm = false, as for genie3: net.pcrnet_denoised re-normalises and
    % re-log1p's by default.
    "pcrnet_denoised", "PCR (tensor-denoised)", ...
    "tensor-denoised PCR on subsampled networks (robust, slow)", ...
    @(X, ~) net.pcrnet_denoised(X, "donorm", false).', ...
    "", false, "pearson_residuals", "", NaN

    "grnformer", "GRNFormer", ...
    "GRNFormer graph transformer (Hegde & Cheng 2026)", ...
    @buildGrnformer, ...
    "tf_idx, Name=Value... -- tf_idx is a logical or integer index of TF " + ...
    "genes; name-value pairs are forwarded to net.grnformer", false, "pearson_residuals", "", NaN

    "tn", "Tensor Network (MPS)", ...
    "tensor-network MPS Born machine (panel-scale, <= ~20 genes)", ...
    @buildTensorNetwork, ...
    "genelist (optional) -- see ten.tngrn for edges and virtual knockouts", ...
    false, "pearson_residuals", "", NaN
    };

T = cell2table(rows, "VariableNames", ["Key", "Label", "Summary", "Build", ...
    "ExtraArgs", "InMenus", "Transform", "RawCountsNote", "SecondsPerPair"]);
end

function A = buildGrnformer(X, extra)
if isempty(extra)
    error("sc_grn:MissingTFIdx", ...
        "grnformer requires tf_idx as the third argument.\n" + ...
        "  Usage: sc_grn(X, 'grnformer', tf_idx, ...)");
end
A = net.grnformer(X, extra{1}, extra{2:end});
end

function A = buildTensorNetwork(X, extra)
genelist = string.empty;
if ~isempty(extra)
    genelist = extra{1};
end
A = ten.tngrn(X, genelist, "EdgesOnly", true);
end
