function T = lectinreagents(panelName)
%LECTINREAGENTS  Lectin reagent -> glycan epitope -> transcript map.
%   T = GLY.LECTINREAGENTS() returns the full curated map of
%   physical lectin reagents (the probes used in lectin microarrays and in
%   oligonucleotide-barcoded lectin single-cell assays such as scGR-seq /
%   scGlycan-seq) to the glycan epitope they bind, the glyco module(s) of
%   GLY.GENESETS whose activity produces that epitope, and the
%   individual biosynthetic transcripts that write or erase it.
%
%   T = GLY.LECTINREAGENTS(panelName) returns the subset of rows
%   belonging to a named panel. Currently supported: "lecchip" (the 45-lectin
%   GlycoStation / LecChip family, of which the scGR-seq panel is a subset)
%   and "all" (default).
%
%   This table is the bridge between MEASURED glyco-state (lectin counts on a
%   cell) and INFERRED glyco-state (GLY.STATE module scores computed from
%   the transcriptome of the same cell). It is a curation asset, not an
%   algorithm: nothing here is fitted.
%
%   OUTPUTS:
%     T - table with columns:
%         Lectin       - reagent short name as it appears in feature tables.
%                        Names are given without punctuation (PHAL, GSLII,
%                        UEAI) because that is how they are written in 10x
%                        Antibody-Capture feature references; use
%                        GLY.LECTINREAGENTS with I_MATCHLECTIN below
%                        or normalise your own names the same way.
%         Epitope      - the glycan determinant bound
%         GlycoModules - comma-separated GLY.GENESETS module names
%                        whose activity produces the epitope
%         WriterGenes  - comma-separated transcripts that BUILD the epitope;
%                        expression should correlate POSITIVELY with binding
%         EraserGenes  - comma-separated transcripts that MASK, cap or remove
%                        the epitope; expression should correlate NEGATIVELY
%                        with binding. Empty where none is known.
%         Description  - human-readable specificity
%
%   The writer/eraser split matters. Several reagents report on the ABSENCE
%   of a downstream step rather than the presence of an upstream one: PNA
%   binds core-1 O-glycan only while it is unsialylated, so ST3GAL1 is an
%   eraser; HPA binds Tn only while it is unextended, so C1GALT1 is an
%   eraser; GSL-II binds terminal GlcNAc only while it is ungalactosylated,
%   so B4GALT1 is an eraser. Correlating those reagents against a writer set
%   alone will look like a failure of the inference when it is a failure of
%   the map.
%
%   Specificities are from the Kuno/Hirabayashi frontal-affinity and
%   evanescent-field lectin microarray series and the CFG lectin database;
%   the transcript assignments follow KEGG glycan biosynthesis and the
%   GlycoGene classification.
%
% see also: GLY.GENESETS, GLY.LECTINMAP, GLY.STATE

arguments
    panelName (1, 1) string = "all"
end

spec = i_reagentspec();

T = table(string(spec(:, 1)), string(spec(:, 2)), string(spec(:, 3)), ...
    string(spec(:, 4)), string(spec(:, 5)), string(spec(:, 6)), ...
    VariableNames = ["Lectin", "Epitope", "GlycoModules", ...
    "WriterGenes", "EraserGenes", "Description"]);

switch lower(panelName)
    case {"all", ""}
        % keep everything
    case {"lecchip", "glycostation", "scgr", "scgrseq"}
        % the whole curated set is the LecChip family at present
    otherwise
        error("LECTINREAGENTS:BadPanel", ...
            "Unknown panel ""%s"".", panelName);
end

end


function spec = i_reagentspec()
% {Lectin, Epitope, GlycoModules, WriterGenes, EraserGenes, Description}
spec = {

% ---- sialic acid ----
"SNA", "Sia_a2_6Gal", ...
"Glyco_sialylation", ...
"ST6GAL1,ST6GAL2", ...
"NEU1,NEU3", ...
"Sia-alpha2,6-Gal/GalNAc on N-glycans (elderberry bark)";

"SSA", "Sia_a2_6Gal", ...
"Glyco_sialylation", ...
"ST6GAL1,ST6GAL2", ...
"NEU1,NEU3", ...
"Sia-alpha2,6-Gal, same arm as SNA (Sambucus sieboldiana)";

"TJAI", "Sia_a2_6Gal_or_sulfoGal", ...
"Glyco_sialylation,Glyco_carbohydrate_sulfotransferases", ...
"ST6GAL1,CHST1", ...
"NEU1", ...
"Sia-alpha2,6-Gal and 6-sulfo-Gal (Trichosanthes japonica I)";

"rPSL1a", "Sia_a2_6LacNAc", ...
"Glyco_sialylation", ...
"ST6GAL1", ...
"NEU1", ...
"Sia-alpha2,6-Gal-beta1,4-GlcNAc, strict (Polyporus squamosus)";

"MAL", "Sia_a2_3LacNAc", ...
"Glyco_sialylation", ...
"ST3GAL3,ST3GAL4,ST3GAL6", ...
"NEU1,NEU3", ...
"Sia-alpha2,3-Gal-beta1,4-GlcNAc on N-glycans (M. amurensis I)";

"MAH", "Sia_a2_3_core1", ...
"Glyco_sialylation,Glyco_O_GalNAc_mucin_type", ...
"ST3GAL1,ST3GAL2", ...
"NEU1", ...
"Sia-alpha2,3-Gal-beta1,3-GalNAc on O-glycans (M. amurensis II)";

"rACG", "Sia_a2_3Gal_or_LacNAc", ...
"Glyco_sialylation,Glyco_galactosylation", ...
"ST3GAL3,ST3GAL4,B4GALT1", ...
"", ...
"Sia-alpha2,3-Gal and Gal-beta1,4-GlcNAc (Agrocybe cylindracea galectin)";

% ---- N-glycan branching / mannose ----
% MGAT1 and MGAT2 are writers although neither makes the beta1,6 branch:
% GnT-I and GnT-II must act before GnT-V has a substrate at all, and the
% genome-wide CRISPR screen in Kearney et al. (Sci Adv 2021;7:eabe3610)
% found guides against Mgat1, Mgat2 AND Mgat5 enriched among L-PHA-negative
% cells. A writer set of MGAT5 alone drops two of the three genes that
% screen named. ST6GAL1 is an eraser on the same footing as ST3GAL1 is for
% PNA: alpha2,6-sialylation caps the branch and abolishes PHA-L binding.
"PHAL", "beta1_6_branch", ...
"Glyco_N_glycan_processing_Golgi", ...
"MGAT5,MGAT4A,MGAT4B,MGAT1,MGAT2", ...
"MGAT3,ST6GAL1", ...
"Tri-/tetra-antennary beta1,6-branched N-glycan (P. vulgaris leucoagglutinin)";

"PHAE", "bisecting_GlcNAc", ...
"Glyco_N_glycan_processing_Golgi", ...
"MGAT3", ...
"MGAT5", ...
"Bisecting GlcNAc, biantennary complex N-glycan (P. vulgaris erythroagglutinin)";

"GNA", "high_mannose_a1_3", ...
"Glyco_N_glycan_biosynthesis_ER", ...
"ALG3,ALG9,ALG12,MOGS", ...
"MAN1A1,MAN1A2,MAN1B1,MGAT1", ...
"Man-alpha1,3-Man of high-mannose N-glycan (Galanthus nivalis)";

"NPA", "high_mannose_a1_6", ...
"Glyco_N_glycan_biosynthesis_ER", ...
"ALG3,ALG9,ALG12,MOGS", ...
"MAN1A1,MAN1A2,MGAT1", ...
"Man-alpha1,6-Man of high-mannose N-glycan (Narcissus pseudonarcissus)";

"rOrysata", "high_mannose", ...
"Glyco_N_glycan_biosynthesis_ER", ...
"ALG3,ALG9,ALG12", ...
"MAN1A1,MGAT1", ...
"High-mannose N-glycan (Oryza sativa jacalin-related lectin)";

% ---- fucose ----
"PSA", "core_fucose", ...
"Glyco_fucosylation", ...
"FUT8", ...
"", ...
"alpha1,6 core fucose on N-glycan, mannose-dependent (Pisum sativum)";

"rAOL", "fucose_broad", ...
"Glyco_fucosylation", ...
"FUT8,FUT1,FUT2,FUT4", ...
"FUCA1,FUCA2", ...
"alpha1,6 core and alpha1,2/3/4 fucose (Aspergillus oryzae lectin)";

"UEAI", "H_type2_Fuc_a1_2", ...
"Glyco_fucosylation", ...
"FUT1,FUT2", ...
"FUCA1", ...
"Fuc-alpha1,2-Gal-beta1,4-GlcNAc, H type 2 (Ulex europaeus I)";

"rBC2LCN", "H_type1_type3_Fuc_a1_2", ...
"Glyco_fucosylation,Glyco_O_GalNAc_mucin_type", ...
"FUT1,FUT2", ...
"FUCA1", ...
"Fuc-alpha1,2-Gal-beta1,3-GlcNAc/GalNAc, H type 1 and 3 (B. cenocepacia)";

"TJAII", "Fuc_a1_2Gal_or_GalNAc", ...
"Glyco_fucosylation", ...
"FUT1,FUT2", ...
"FUCA1", ...
"Fuc-alpha1,2-Gal and terminal GalNAc (Trichosanthes japonica II)";

"rF17AG", "terminal_GlcNAc", ...
"Glyco_hexosamine_biosynthesis,Glyco_N_glycan_processing_Golgi", ...
"MGAT1,MGAT2", ...
"B4GALT1,B4GALT2", ...
"GlcNAc-terminated glycan (E. coli F17-G adhesin domain)";

% ---- galactose / LacNAc ----
"rGal3C", "polyLacNAc", ...
"Glyco_galactosylation", ...
"B4GALT1,B3GNT2,B3GNT8", ...
"ST3GAL4,ST6GAL1", ...
"Poly-LacNAc, Gal-beta1,4-GlcNAc repeats (human galectin-3 CRD)";

"rLSLN", "LacNAc", ...
"Glyco_galactosylation", ...
"B4GALT1,B4GALT2", ...
"", ...
"Gal-beta1,4-GlcNAc and sialyl-LacNAc (Laetiporus sulphureus N-domain)";

"rMOA", "Gal_a1_3Gal", ...
"Glyco_galactosylation", ...
"A4GALT,B3GALNT1", ...
"", ...
"Gal-alpha1,3-Gal / Gal-alpha1,4-Gal (Marasmius oreades). Note: GGTA1 is a human pseudogene, so a human signal here is largely Gb3/P1";

% ---- O-glycan core 1 / T antigen ----
"PNA", "T_antigen_unsialylated", ...
"Glyco_O_GalNAc_mucin_type", ...
"C1GALT1,C1GALT1C1", ...
"ST3GAL1,ST3GAL2,ST6GALNAC1,ST6GALNAC2,GCNT1", ...
"Gal-beta1,3-GalNAc, T antigen, ONLY when unsialylated (peanut)";

"MPA", "T_antigen_and_GalNAc", ...
"Glyco_O_GalNAc_mucin_type", ...
"C1GALT1,C1GALT1C1,GALNT1,GALNT2", ...
"ST3GAL1,ST6GALNAC1", ...
"Gal-beta1,3-GalNAc-alpha and alpha-GalNAc (Maclura pomifera)";

"BPL", "T_antigen_and_Gal", ...
"Glyco_O_GalNAc_mucin_type,Glyco_galactosylation", ...
"C1GALT1,C1GALT1C1,B4GALT1", ...
"ST3GAL1", ...
"Gal-beta1,3-GalNAc and terminal Gal (Bauhinia purpurea)";

% ---- GalNAc / Tn / LacdiNAc ----
"HPA", "Tn_antigen", ...
"Glyco_O_GalNAc_mucin_type", ...
"GALNT1,GALNT2,GALNT3,GALNT6", ...
"C1GALT1,C1GALT1C1,ST6GALNAC1", ...
"GalNAc-alpha-Ser/Thr, Tn antigen, ONLY when unextended (Helix pomatia)";

"rPTL", "GalNAc_Tn_T", ...
"Glyco_O_GalNAc_mucin_type", ...
"GALNT1,GALNT2,GALNT3", ...
"ST6GALNAC1", ...
"alpha-GalNAc, Tn and T antigen (Psophocarpus tetragonolobus)";

"WFA", "LacdiNAc_and_sulfoGalNAc", ...
"Glyco_O_GalNAc_mucin_type,Glyco_carbohydrate_sulfotransferases", ...
"B4GALNT3,B4GALNT4,CHST8,CHST9,GALNT1", ...
"", ...
"GalNAc-beta1,4-GlcNAc (LacdiNAc), terminal and 6-sulfo GalNAc (Wisteria floribunda)";

% ---- GlcNAc / chitobiose ----
"WGA", "GlcNAc_and_sialic_acid", ...
"Glyco_hexosamine_biosynthesis,Glyco_sialylation", ...
"GFPT1,GNPNAT1,UAP1,OGT,ST3GAL4,ST6GAL1", ...
"", ...
"GlcNAc, (GlcNAc)n and sialic acid, broad (wheat germ agglutinin)";

"PVL", "terminal_GlcNAc", ...
"Glyco_hexosamine_biosynthesis,Glyco_N_glycan_processing_Golgi", ...
"MGAT1,MGAT2,MGAT4A", ...
"B4GALT1", ...
"Non-reducing terminal GlcNAc, also sialyl-LacNAc (Psathyrella velutina)";

"GSLII", "agalacto_terminal_GlcNAc", ...
"Glyco_N_glycan_processing_Golgi", ...
"MGAT1,MGAT2,MGAT4A,MGAT5", ...
"B4GALT1,B4GALT2,B4GALT3", ...
"Agalactosylated terminal GlcNAc, alpha or beta (Griffonia simplicifolia II)";

% ---- control ----
"Mouse_IgG1", "none_isotype_control", ...
"", ...
"", ...
"", ...
"Isotype control, not a lectin. Use as the background/ambient estimate";

};
end
