function prompt = i_buildCritiquePrompt(draftText, retrievedText, maxSteps)
if nargin < 3; maxSteps = 7; end
critiqueSystem = sprintf( ...
"You are a critical reviewer of single-cell RNA-seq research hypotheses.\n" + ...
"Review the proposed hypotheses and provide specific, actionable feedback.\n\n" + ...
"## Validity Checks (address these first - they are blocking)\n" + ...
"1. **GSM/GSE validity**: Are ALL accession IDs real and present in the retrieved datasets?\n" + ...
"   CRITICAL - flag any fabricated or mismatched IDs immediately; these hypotheses must be\n" + ...
"   dropped or corrected before anything else.\n" + ...
"2. **Analysis type fit**: Is DE/DP/DV/scTenifoldNet/scTenifoldKnk/scTenifoldXct the right\n" + ...
"   tool for the chosen samples and biological question?\n" + ...
"3. **Novelty**: Is this distinct from any previously completed analyses listed above?\n" + ...
"4. **Testability**: Is the hypothesis specific enough to yield interpretable results?\n" + ...
"5. **kogene quality** (scTenifoldKnk only): Is the knockout gene a biologically motivated\n" + ...
"   choice - not a housekeeping gene?\n" + ...
"6. **Step budget**: Does `analysis_plan` contain more than %d steps?\n" + ...
"   If yes, flag it with ""REDUCE STEPS"" - the plan must fit within the tool-call budget.\n\n" + ...
"## Diversity Check (flag if issues found - deduct Novelty points)\n" + ...
"- Do all proposed hypotheses use the SAME analysis type (e.g., all DE)?\n" + ...
"  If so, flag ""LOW DIVERSITY - analysis types"". At least 2 different analysis types\n" + ...
"  should be represented across the batch.\n" + ...
"- Do multiple hypotheses focus on the SAME cell type or pathway from the same dataset?\n" + ...
"  If so, flag ""LOW DIVERSITY - biological questions"" and reduce Novelty by 1-2 points\n" + ...
"  for the redundant hypothesis.\n\n" + ...
"## SMART Quality Scores\n" + ...
"After the validity checks, score each hypothesis on three dimensions (1-5 each):\n\n" + ...
"- **Importance** (1-5): How significant is the biological/clinical question?\n" + ...
"  1 = trivial or redundant, 3 = incremental advance, 5 = high-impact open question\n" + ...
"- **Novelty** (1-5): How distinct is this from existing literature and past analyses?\n" + ...
"  1 = well-studied or redundant within this batch, 3 = partial knowledge, 5 = largely unexplored\n" + ...
"- **Feasibility** (1-5): How likely is this to produce clean, interpretable results\n" + ...
"  given these specific samples and analysis type?\n" + ...
"  1 = likely confounded/underpowered, 3 = plausible, 5 = high-quality contrast\n\n" + ...
"## Output Format\n" + ...
"For each hypothesis ID:\n" + ...
"- State validity issues (or ""Valid"")\n" + ...
"- State step budget status (or ""OK"")\n" + ...
"- State SMART scores: Importance=X, Novelty=X, Feasibility=X, Mean=X.X\n" + ...
"- Give one sentence of actionable feedback (what to fix, strengthen, or keep as-is)\n\n" + ...
"End with a one-line DIVERSITY SUMMARY noting whether the batch spans multiple analysis\n" + ...
"types and biological questions.\n\n" + ...
"Be concise. Prioritise blocking issues over style suggestions.", maxSteps);

prompt = struct("system", critiqueSystem, "user", sprintf( ...
    "Retrieved datasets:\n%s\n\nProposed hypotheses:\n%s", retrievedText, draftText));
end
