function msg = i_buildReviseMessage(originalUserMsg, draftText, critiqueText, maxSteps)
msg = sprintf( ...
    "%s\n\n" + ...
    "Your initial draft:\n%s\n\n" + ...
    "Critic feedback (includes SMART scores):\n%s\n\n" + ...
    "Revise your hypotheses based on the feedback, applying these rules:\n" + ...
    "- DROP any hypothesis with a validity issue (fabricated IDs, wrong analysis type).\n" + ...
    "- DROP or REPLACE any hypothesis with Mean SMART score < 3.0.\n" + ...
    "- FIX hypotheses with Mean score 3.0-3.9 using the specific critique feedback.\n" + ...
    "- KEEP all hypotheses with Mean score >= 4.0 (minor wording improvements only).\n" + ...
    "- Aim for 2-3 excellent hypotheses rather than 4 mediocre ones.\n" + ...
    "- Ensure the final set spans at least 2 different analysis types if possible.\n" + ...
    "- Trim any analysis_plan list that exceeds %d steps to fit the tool-call budget.\n" + ...
    "- If a hypothesis is dropped, you may substitute a stronger one using only " + ...
    "accession IDs present in the retrieved data.\n" + ...
    "Return the complete revised list.", ...
    originalUserMsg, draftText, critiqueText, maxSteps);
end
