function [txt, stop] = i_tamu_http(chat, msgs, cfg, logFcn, passName)
% Direct HTTP call to TAMU API, bypassing openAIChat's SSE parser.
% The reply is read by llm.geocellar.i_parsecompletion, which throws when it
% holds no completion rather than returning an empty one.
apiKey = char(cfg.OpenAIAPIKey);
url    = [regexprep(char(chat.BaseURL), '/$', '') '/chat/completions'];
model  = char(chat.ModelName);

allMsgs = chat.SystemPrompt;
for k = 1:numel(msgs.Messages)
    m = msgs.Messages{k};
    allMsgs{end+1} = struct('role', char(m.role), 'content', char(m.content)); %#ok<AGROW>
end

reqBody = jsonencode(struct( ...
    'model',      model, ...
    'messages',   {allMsgs}, ...
    'stream',     false, ...
    'max_tokens', 8192 ...
));

opts = weboptions( ...
    'HeaderFields', {'Authorization', ['Bearer ' apiKey]; ...
                     'Content-Type',  'application/json'}, ...
    'RequestMethod', 'post', ...
    'Timeout',       300, ...
    'ContentType',   'text' ...
);

responseText = webwrite(url, reqBody, opts);
[txt, stop] = llm.geocellar.i_parsecompletion(responseText);
logFcn(sprintf("%s [direct]: %d chars.", passName, strlength(txt)));
end
