function callback_SaveX(src,~)
answer = questdlg('Export & save data?');
if ~strcmp(answer,'Yes'), return; end     
    FigureHandle=src.Parent.Parent;
    sce=guidata(FigureHandle);
    labels = {'Save SCE to variable named:',...
        'Save SCE.X to variable named:',...
        'Save SCE.g to variable named:',...
        'Save SCE.S to variable named:'}; 
    vars = {'sce','X','genelist','s'};
    values = {sce,sce.X,sce.g,sce.s};
    export2wsdlg(labels,vars,values,...
        'Save Data to Workspace',...
        logical([1 0 0 0]),{@smhelp});
         
    function smhelp
        helpdlg({'Select one or both check boxes.',...
                 'Change the variable names, if desired,',...
                 'and then click OK.'});
    end
end
