function [setmatrx, setnames, setgenes, T] = e_glycogenesets(exportGmtFile)
%E_GLYCOGENESETS  Curated glycobiology gene-set collection.
%   [setmatrx, setnames, setgenes] = PKG.E_GLYCOGENESETS() returns a curated
%   collection of glycobiology-related gene sets in the same form produced by
%   PKG.E_GETGENESETS. Each gene set is a functional module of the glycome
%   machinery (glycan biosynthesis, degradation, transport, and recognition).
%   Scoring cells against these sets (e.g. with SC_GLYCOSTATE) yields a
%   per-cell, per-module readout that collectively defines a cell's
%   glycobiological state.
%
%   [setmatrx, setnames, setgenes, T] = PKG.E_GLYCOGENESETS() also returns a
%   table T with the columns Name, Description, Reference, and Genes.
%
%   PKG.E_GLYCOGENESETS(exportGmtFile) additionally writes the collection to
%   exportGmtFile in GMT format (name<TAB>description<TAB>gene1<TAB>gene2...).
%
%   OUTPUTS:
%     setmatrx - M-by-G logical membership matrix (M sets x G unique genes)
%     setnames - M-by-1 string array of gene-set names
%     setgenes - G-by-1 string array of unique gene symbols (union of all sets)
%     T        - M-by-4 table describing the collection
%
%   The gene symbols are human (HGNC) and are matched case-insensitively by
%   the scoring functions, so mouse orthologues that share a spelling still
%   match. A few genes are listed under both their current and legacy symbols
%   (e.g. OGA/MGEA5, GFUS/TSTA3) so the sets match regardless of annotation.
%
%   Curated from KEGG glycan pathways, GO glycosylation terms, the CAZy /
%   GlycoGene classification, and the CFG glycogene lists.
%
% see also: SC_GLYCOSTATE, PKG.E_GETGENESETS, SC_CELLSCORE

arguments
    exportGmtFile (1,1) string = ""
end

spec = i_glycospec();

setnames = string(spec(:, 1));
descriptions = string(spec(:, 2));
references = string(spec(:, 3));

nSets = size(spec, 1);
geneCell = cell(nSets, 1);
for k = 1:nSets
    geneCell{k} = pkg.i_str2genelist(spec{k, 4});
end

setgenes = unique(vertcat(geneCell{:}));
setgenes = setgenes(strlength(setgenes) > 0);

setmatrx = false(nSets, numel(setgenes));
for k = 1:nSets
    setmatrx(k, :) = ismember(upper(setgenes), upper(geneCell{k}));
end

joinedGenes = strings(nSets, 1);
for k = 1:nSets
    joinedGenes(k) = strjoin(geneCell{k}, ",");
end
T = table(setnames, descriptions, references, joinedGenes, ...
    VariableNames=["Name", "Description", "Reference", "Genes"]);

if strlength(exportGmtFile) > 0
    i_writegmt(exportGmtFile, setnames, descriptions, geneCell);
end

end


%% ---- write the collection to a GMT file ----
function i_writegmt(gmtFile, setnames, descriptions, geneCell)
fid = fopen(gmtFile, "w");
if fid < 0
    error("Cannot open file for writing: %s", gmtFile);
end
cleanupObj = onCleanup(@() fclose(fid));
for k = 1:numel(setnames)
    fields = [setnames(k); descriptions(k); geneCell{k}(:)];
    fprintf(fid, "%s\n", strjoin(fields, sprintf("\t")));
end
end


%% ---- curated glycobiology gene-set specification ----
function spec = i_glycospec()
% Each row is {Name, Description, Reference, comma-separated gene symbols}.
spec = {

"Glyco_N_glycan_biosynthesis_ER", ...
"N-glycan lipid-linked oligosaccharide assembly and en-bloc transfer (OST)", ...
"KEGG hsa00510", ...
"DPAGT1,ALG1,ALG2,ALG3,ALG5,ALG6,ALG8,ALG9,ALG10,ALG11,ALG12,ALG13,ALG14," + ...
"RFT1,DPM1,DPM2,DPM3,MPDU1,DOLK,SRD5A3,DHDDS,NUS1,STT3A,STT3B,RPN1,RPN2," + ...
"DDOST,DAD1,OSTC,MAGT1,TUSC3";

"Glyco_N_glycan_processing_Golgi", ...
"N-glycan trimming and branching in the Golgi", ...
"KEGG hsa00510", ...
"MOGS,GANAB,MAN1A1,MAN1A2,MAN1B1,MAN1C1,MAN2A1,MAN2A2,MGAT1,MGAT2,MGAT3," + ...
"MGAT4A,MGAT4B,MGAT4C,MGAT5,MGAT5B,B4GALT1,ST6GAL1,FUT8";

"Glyco_O_GalNAc_mucin_type", ...
"Mucin-type O-GalNAc glycan initiation and core extension", ...
"KEGG hsa00512", ...
"GALNT1,GALNT2,GALNT3,GALNT4,GALNT5,GALNT6,GALNT7,GALNT8,GALNT9,GALNT10," + ...
"GALNT11,GALNT12,GALNT13,GALNT14,GALNT15,GALNT16,GALNT18,C1GALT1,C1GALT1C1," + ...
"GCNT1,GCNT3,GCNT4,B3GNT6,ST3GAL1,ST6GALNAC1,ST6GALNAC2";

"Glyco_O_GlcNAc_cycling", ...
"Nucleocytoplasmic O-GlcNAc addition and removal (nutrient sensing)", ...
"GO:0006493", ...
"OGT,OGA,MGEA5,GFPT1,GFPT2,GNPNAT1,PGM3,UAP1,NAGK";

"Glyco_hexosamine_biosynthesis", ...
"Hexosamine biosynthetic pathway (UDP-GlcNAc / CMP-sialic acid supply)", ...
"GO:0006047", ...
"GFPT1,GFPT2,GNPNAT1,PGM3,UAP1,NAGK,GNPDA1,GNPDA2,GNE,NANS,CMAS,SLC35A1,OGT,OGA";

"Glyco_sialylation", ...
"Sialyltransferases and CMP-sialic acid biosynthesis", ...
"CAZy GT29 / GO:0097503", ...
"ST3GAL1,ST3GAL2,ST3GAL3,ST3GAL4,ST3GAL5,ST3GAL6,ST6GAL1,ST6GAL2,ST6GALNAC1," + ...
"ST6GALNAC2,ST6GALNAC3,ST6GALNAC4,ST6GALNAC5,ST6GALNAC6,ST8SIA1,ST8SIA2," + ...
"ST8SIA3,ST8SIA4,ST8SIA5,ST8SIA6,GNE,NANS,NANP,CMAS,SLC35A1";

"Glyco_sialidases", ...
"Sialidases / neuraminidases (desialylation)", ...
"GO:0004308", ...
"NEU1,NEU2,NEU3,NEU4";

"Glyco_fucosylation", ...
"Fucosyltransferases and GDP-fucose supply", ...
"CAZy GT10/GT23 / GO:0036065", ...
"FUT1,FUT2,FUT3,FUT4,FUT5,FUT6,FUT7,FUT8,FUT9,FUT10,FUT11,POFUT1,POFUT2," + ...
"GMDS,GFUS,TSTA3,FPGT,SLC35C1";

"Glyco_galactosylation", ...
"Galactosyltransferases and galactose (Leloir) metabolism", ...
"CAZy GT7/GT31 / GO:0006486", ...
"B4GALT1,B4GALT2,B4GALT3,B4GALT4,B4GALT5,B4GALT6,B4GALT7,B3GALT1,B3GALT2," + ...
"B3GALT4,B3GALT5,B3GALT6,A4GALT,GLB1,GALE,GALK1,GALT";

"Glyco_heparan_sulfate_biosynthesis", ...
"Heparan sulfate chain polymerization and modification", ...
"KEGG hsa00534", ...
"EXT1,EXT2,EXTL1,EXTL2,EXTL3,NDST1,NDST2,NDST3,NDST4,GLCE,HS2ST1,HS3ST1," + ...
"HS3ST2,HS3ST3A1,HS3ST3B1,HS3ST4,HS3ST5,HS3ST6,HS6ST1,HS6ST2,HS6ST3," + ...
"XYLT1,XYLT2,B4GALT7,B3GALT6,B3GAT3,SULF1,SULF2";

"Glyco_chondroitin_dermatan_sulfate", ...
"Chondroitin and dermatan sulfate biosynthesis", ...
"KEGG hsa00532", ...
"CSGALNACT1,CSGALNACT2,CHSY1,CHSY3,CHPF,CHPF2,CHST3,CHST7,CHST11,CHST12," + ...
"CHST13,CHST14,CHST15,DSE,DSEL,UST,XYLT1,XYLT2,B4GALT7,B3GALT6,B3GAT3";

"Glyco_keratan_sulfate", ...
"Keratan sulfate biosynthesis", ...
"KEGG hsa00533", ...
"B3GNT7,B4GALT4,CHST1,CHST2,CHST5,CHST6,ST3GAL1,ST3GAL3";

"Glyco_hyaluronan_metabolism", ...
"Hyaluronan synthesis and turnover", ...
"GO:0030212", ...
"HAS1,HAS2,HAS3,HYAL1,HYAL2,HYAL3,HYAL4,CEMIP,CEMIP2,SPAM1";

"Glyco_glycosphingolipid_biosynthesis", ...
"Glycosphingolipid (ganglio/globo/lacto) biosynthesis", ...
"KEGG hsa00600/00601/00603/00604", ...
"UGCG,UGT8,B4GALT5,B4GALT6,ST3GAL5,B4GALNT1,B3GALT4,ST8SIA1,ST8SIA5,A4GALT," + ...
"B3GNT5,ST3GAL2,GBGT1,GAL3ST1,B3GALNT1";

"Glyco_glycan_lysosomal_degradation", ...
"Lysosomal glycosidases and sulfatases (glycan/GAG/GSL degradation)", ...
"KEGG hsa00511/00531", ...
"GBA,GBA2,GLB1,HEXA,HEXB,GM2A,GALC,ARSA,GLA,NAGA,MAN2B1,MAN2B2,MANBA,FUCA1," + ...
"FUCA2,NEU1,AGA,NAGLU,GNS,GUSB,IDUA,IDS,SGSH,HGSNAT,GALNS,ARSB,HPSE,HPSE2," + ...
"SMPD1,ASAH1,PSAP";

"Glyco_GPI_anchor_biosynthesis", ...
"Glycosylphosphatidylinositol (GPI) anchor biosynthesis and remodeling", ...
"KEGG hsa00563", ...
"PIGA,PIGB,PIGC,PIGF,PIGG,PIGH,PIGK,PIGL,PIGM,PIGN,PIGO,PIGP,PIGQ,PIGS,PIGT," + ...
"PIGU,PIGV,PIGW,PIGX,PIGY,PIGZ,GPAA1,PGAP1,PGAP2,PGAP3,PGAP4,PGAP6,MPPE1,DPM2";

"Glyco_ER_glycoprotein_quality_control", ...
"Calnexin/calreticulin cycle and glycan-dependent ERAD", ...
"GO:0006986 / R-HSA-901042", ...
"CANX,CALR,UGGT1,UGGT2,MOGS,GANAB,MAN1B1,EDEM1,EDEM2,EDEM3,OS9,PRKCSH,MLEC," + ...
"LMAN1,LMAN2,SEL1L,HERPUD1,DNAJC10";

"Glyco_nucleotide_sugar_metabolism", ...
"Biosynthesis and interconversion of nucleotide sugar donors", ...
"GO:0009225", ...
"UGP2,UAP1,UAP1L1,GALE,GALK1,GALK2,GALT,PGM1,PGM2,PGM3,GMDS,GFUS,TSTA3,GNE," + ...
"CMAS,NANS,NANP,UXS1,UGDH,GFPT1,GFPT2,GMPPA,GMPPB,MPI,PMM1,PMM2,GNPNAT1";

"Glyco_nucleotide_sugar_transporters", ...
"SLC35 family nucleotide sugar transporters", ...
"SLC35 / GO:0015780", ...
"SLC35A1,SLC35A2,SLC35A3,SLC35A4,SLC35A5,SLC35B1,SLC35B2,SLC35B3,SLC35B4," + ...
"SLC35C1,SLC35C2,SLC35D1,SLC35D2,SLC35D3,SLC35E1,SLC35E2,SLC35E3,SLC35E4," + ...
"SLC35F1,SLC35F2,SLC35F3,SLC35F4,SLC35F5,SLC35F6,SLC35G1";

"Glyco_O_mannosylation_dystroglycan", ...
"O-mannosylation and the alpha-dystroglycan matriglycan pathway", ...
"KEGG hsa00515", ...
"POMT1,POMT2,POMGNT1,POMGNT2,B4GAT1,B3GNT2,LARGE1,LARGE2,FKTN,FKRP,CRPPA," + ...
"ISPD,RXYLT1,TMEM5,POMK,DAG1,DPM1,DPM2,DPM3,GMPPB";

"Glyco_Notch_EGF_O_glycosylation", ...
"O-fucose/O-glucose glycosylation of EGF repeats and Fringe modification", ...
"GO:0018345 / R-HSA-1912399", ...
"POFUT1,POFUT2,POGLUT1,POGLUT2,POGLUT3,LFNG,MFNG,RFNG,GXYLT1,GXYLT2,XXYLT1," + ...
"B3GLCT,KDELC1,KDELC2";

"Glyco_carbohydrate_sulfotransferases", ...
"Carbohydrate sulfotransferases and endosulfatases", ...
"GO:0008146", ...
"CHST1,CHST2,CHST3,CHST4,CHST5,CHST6,CHST7,CHST8,CHST9,CHST10,CHST11,CHST12," + ...
"CHST13,CHST14,CHST15,GAL3ST1,GAL3ST2,GAL3ST3,GAL3ST4,NDST1,NDST2,NDST3," + ...
"NDST4,HS2ST1,HS3ST1,HS6ST1,HS6ST2,HS6ST3,UST,SULF1,SULF2";

"Glyco_galectins", ...
"Galectins (S-type beta-galactoside-binding lectins)", ...
"GO:0005534", ...
"LGALS1,LGALS2,LGALS3,LGALS3BP,LGALS4,LGALS7,LGALS7B,LGALS8,LGALS9,LGALS9B," + ...
"LGALS9C,LGALS12,LGALS13,LGALS14,LGALS16,LGALSL,GRIFIN";

"Glyco_siglecs", ...
"Siglecs (sialic acid-binding immunoglobulin-type lectins)", ...
"GO:0033691", ...
"SIGLEC1,CD22,SIGLEC5,SIGLEC6,SIGLEC7,SIGLEC8,SIGLEC9,SIGLEC10,SIGLEC11," + ...
"SIGLEC12,SIGLEC14,SIGLEC15,SIGLEC16,CD33,MAG";

"Glyco_selectins_and_ligands", ...
"Selectins and the enzymes that build their sialyl-Lewis-x ligands", ...
"GO:0070492", ...
"SELL,SELE,SELP,SELPLG,CD44,GLYCAM1,MADCAM1,CD34,PODXL,FUT7,FUT4,ST3GAL4," + ...
"ST3GAL6,GCNT1,B3GNT3";

"Glyco_C_type_lectins", ...
"C-type lectins and collectins (glycan recognition)", ...
"GO:0005537", ...
"MRC1,MRC2,CD209,CLEC4A,CLEC4C,CLEC4D,CLEC4E,CLEC4G,CLEC4M,CLEC7A,CLEC9A," + ...
"CLEC10A,CLEC12A,CLEC1A,CLEC1B,CLEC2B,CLEC2D,CD207,ASGR1,ASGR2,LMAN1," + ...
"COLEC10,COLEC11,COLEC12,MBL2,SFTPA1,SFTPD";

"Glyco_proteoglycan_core_proteins", ...
"Proteoglycan core proteins (GAG scaffolds)", ...
"GO:0005539", ...
"DCN,BGN,LUM,FMOD,PRELP,OGN,ASPN,OMD,KERA,EPYC,VCAN,ACAN,BCAN,NCAN,HSPG2," + ...
"SDC1,SDC2,SDC3,SDC4,GPC1,GPC2,GPC3,GPC4,GPC5,GPC6,SRGN,AGRN,CSPG4,CSPG5";

};
end
