function [T, Tnt] = in_DVTableProcess(T, ~, ~)

        if nargout>1

            Item = T.Properties.VariableNames';
            %Item = [Item; {'# of cells in sample 1';'# of cells in sample 2'}];
            
            % Description = {'gene name';'log mean in sample 1';...
            %     'log CV in sample 1'; 'dropout rate in sample 1';...
            %     'distance to curve 1';'p-value of distance in sample 1';...
            %     'FDR of distance in sample 1';'log mean in sample 2';...
            %     'log CV in sample 2'; 'dropout rate in sample 2';...
            %     'distance to curve 2'; 'p-value of distance in sample 2';...
            %     'FDR of distance in sample 2'; 'Difference in distances';...
            %     'Sign of difference';'p-value of DV test';...
            %     sprintf('%d',sce1.NumCells); sprintf('%d',sce2.NumCells)};

            Description = {'gene name';'log mean in sample 1';...
                'log CV in sample 1'; 'dropout rate in sample 1';...
                'distance to curve 1';'p-value of distance in sample 1';...
                'FDR of distance in sample 1';'log mean in sample 2';...
                'log CV in sample 2'; 'dropout rate in sample 2';...
                'distance to curve 2'; 'p-value of distance in sample 2';...
                'FDR of distance in sample 2'; 'Difference in distances';...
                'Sign of difference';'p-value of DV test'};
            
            if length(Item) == length(Description)
                Tnt = table(Item, Description);
            else
                assignin("base","Item", Item);
                assignin("base","Description", Description);
                Tnt = table(Item);
                warning('Variables must have the same number of rows.');
            end
        end

end



