function [T] = makeattributestable(sce)

    T = table(sce.c_cell_id, ...
        sce.c_batch_id, ...
        sce.c_cluster_id, ...
        sce.c_cell_type_tx, ...
        sce.c_cell_cycle_tx, ...
        'VariableNames', {'CellID', 'BatchID', 'ClusterID', ...
        'CellType', 'CellCycle'});
    if ~isempty(sce.list_cell_attributes)        
        for k = 1:2:length(sce.list_cell_attributes)
            T = addvars(T, string(sce.list_cell_attributes{k+1}), ...
                'NewVariableNames', sce.list_cell_attributes{k});
        end
    end
    % obj.table_attributes = T;
    %disp('table_attributes made.');
end