function [T] = makeattributestable(sce)

    T = table(sce.c_cell_id, ...
        sce.c_batch_id, ...
        sce.c_cluster_id, ...
        sce.c_cell_type_tx, ...
        sce.c_cell_cycle_tx, ...
        'VariableNames', {'CellID', 'BatchID', 'ClusterID', ...
        'CellType', 'CellCycle'});
    names = sce.list_cell_attributes(1:2:end);
    for k = 1:numel(names)
        T = addvars(T, string(sce.list_cell_attributes{2*k}), ...
            'NewVariableNames', names{k});
    end
    % obj.table_attributes = T;
    %disp('table_attributes made.');
end